server.servlet.context-path=/api
spring.datasource.url=${AZURE_MYSQL_CONNECTIONSTRING}
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.globally_quoted_identifiers_skip_column_definitions=true
spring.jpa.properties.hibernate.check_nullability=true
springdoc.show-actuator=true
springdoc.packages-to-scan=me.heyner.inventorypro.controller
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=${KEY_VAULT_ENDPOINT}
spring.cloud.azure.keyvault.secret.endpoint=${KEY_VAULT_ENDPOINT}
spring.cloud.azure.keyvault.secret.property-source-enabled=true
security.jwt.secret-key=${jwt-key}
security.jwt.expiration-time=3600000
