spring.jpa.hibernate.ddl-auto=create
spring.cloud.azure.keyvault.enabled=false
spring.cloud.azure.keyvault.secret.property-source-enabled=false
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://example.com/disabled
spring.cloud.azure.keyvault.secret.endpoint=https://example.com/disabled
spring.datasource.url=jdbc:h2:~/development-inventorypro
security.jwt.secret-key=88cd2108b5347d973cf39cdf9053d7dd42704876d8c9a9bd8e2d168259d3ddf7
